// Package mobile provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package mobile

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for Status.
const (
	Available Status = "available"
	Booked    Status = "booked"
	Busy      Status = "busy"
	Hidden    Status = "hidden"
)

// AdminSlot defines model for AdminSlot.
type AdminSlot struct {
	Status Status `json:"status"`
}

// BookingAPI defines model for BookingAPI.
type BookingAPI struct {
	Id int `json:"id"`
}

// BookingAdminAPI defines model for BookingAdminAPI.
type BookingAdminAPI struct {
	Id   int  `json:"id"`
	User User `json:"user"`
}

// Slot defines model for Slot.
type Slot struct {
	Status Status `json:"status"`
}

// Status defines model for Status.
type Status string

// User defines model for User.
type User = string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin)
	GetAdmin(ctx echo.Context) error

	// (GET /who)
	GetWho(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdmin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdmin(ctx)
	return err
}

// GetWho converts echo context to params.
func (w *ServerInterfaceWrapper) GetWho(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWho(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin", wrapper.GetAdmin)
	router.GET(baseURL+"/who", wrapper.GetWho)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xTPW/bMBD9K8VrR8JS241buhSeGjQIOgQZaOlsMZHvWPKUIjD43wtSdu2mRtwpGkQS",
	"x/fBd+QOnWyDMLEm2B1SN9DW1elVv/V8M4qWhRvHb2vYux0+RFrD4n1zBDZ7VFN3Z7NDiD5QVE+VyfNa",
	"yvga9IvIo+dNFb26XiJng0g/Jx+ph72bOe4N9DkQLGT1QJ0i32eDA/R6WURClFPpvvz3IM9KG4r/cvdn",
	"mI+8B0v/HcOJoTmMU0dTongpjNt0xmUFnk/g0KW/lZI6ndIlrZt510u1Pbiy/+Ehnral6J6cH91qJBis",
	"pvQMg8H3PXFZizzSaaBJo+dNCfR2f/QXhSJ9uCLqdSy17xTknVJSGDxRTF4YFu2iXXwsTBKIXfCw+Lxo",
	"Fy0MgtOhemxc6VeZbaiGUiJx6oWXPSy+ktaGohw3BeE0h/WpbcvQCSvxfOVDGH1Xkc1DEj4+j0uRHl9O",
	"nj+D5tcgr3n6McibOsr5dwAAAP//6XKBN/oDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
